blank_issues_enabled: false
contact_links:
  - name: 讨论交流 (QQ 频道) / Communication
    url: https://pd.qq.com/s/61kmagm1v
    about: 在 QQ 频道中与其它用户讨论交流、分享术语表或反馈问题 / Communicate with other users, share glossaries, or report issues in the QQ Channel
